resolvendo problemas de conflitos

diff --git a/.github/workflows/02-bugfix.yml b/.github/workflows/02-bugfix.yml
--- a/.github/workflows/02-bugfix.yml
+++ b/.github/workflows/02-bugfix.yml
@@ -1,289 +1,280 @@
 name: ci-bugfix
 
 on:
-  push:
-    branches:
-      - 'bugfix/**'
+    push:
+        branches:
+            - 'bugfix/**'
 
 env:
-  ENV_CHECKOUT_CACHE: 'npm'
-  ENV_NODE_VERSION: '16.x'
-  ENV_REGISTRY_URL: 'https://npm.pkg.github.com'
-  ENV_NODE_ENV: 'production'
-  ENV_GIT_USERNAME: 'Filipe Santos'
-  ENV_GIT_EMAIL: 'filipe.l.santos@galp.com'
-  ENV_KUBERNETES: 'dev'
+    ENV_CHECKOUT_CACHE: 'npm'
+    ENV_NODE_VERSION: '16.x'
+    ENV_REGISTRY_URL: 'https://npm.pkg.github.com'
+    ENV_NODE_ENV: 'development'
+    ENV_GIT_USERNAME: 'Filipe Santos'
+    ENV_GIT_EMAIL: 'filipe.l.santos@galp.com'
 
 jobs:
 
-  kuberentes:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout source code
-        uses: actions/checkout@v3
+    kuberentes:
+        runs-on: ubuntu-latest
+        steps:
+            - name: Checkout source code
+              uses: actions/checkout@v3
 
-      - name: ls
-        run: |
-           ls
+            - name: Replace Kubernetes Variables
+              run: |
+                  YAML_FILE="infra/kubernetes.yaml"
+                  while IFS= read -r line; do
+                    while [[ $line =~ \$\{([a-zA-Z0-9_]+)\} ]]; do
+                      var_name=${BASH_REMATCH[1]}
+                      var_value=$(echo "${!var_name}")
+                      line=${line//${BASH_REMATCH[0]}/$var_value}
+                    done
+                    echo "$line" >> "${YAML_FILE}_new"
+                  done < "$YAML_FILE"
+                  mv "${YAML_FILE}_new" "$YAML_FILE"
 
-      - name: Replace Kubernetes Variables
-        run: |
-          YAML_FILE="infra/kubernetes.yaml"
-          while IFS= read -r line; do
-            while [[ $line =~ \$\{([a-zA-Z0-9_]+)\} ]]; do
-              # Extrai o nome da variável
-              var_name=${BASH_REMATCH[1]}
+            - name: cat
+              run: |
+                  cat ./infra/kubernetes.yaml
 
-              # Obtém o valor da variável do Secret do GitHub
-              var_value=${var_name}
-              # Substitui a variável no arquivo YAML
-              line=${line//${BASH_REMATCH[0]}/$var_value}
-            done
-            echo "$line" >> "${YAML_FILE}_new"
-          done < "$YAML_FILE"
-          mv "${YAML_FILE}_new" "$YAML_FILE"
+    scan-git:
+        needs: [ kuberentes ]
+        runs-on: ubuntu-latest
+        steps:
+            - name: Checkout repository
+              uses: actions/checkout@v3
 
-      - name: cat
-        run: |
-         cat ./infra/kubernetes.yaml
+            - name: Validate if commit follows the pattern in description "#<number> - description"
+              run: |
+                  if ! git log -1 --pretty=%B | grep -qE '.+'; then
+                    echo "Error: Commit description does not follow the pattern 'description'"
+                    exit 1
+                  fi
 
-  scan-git:
-    needs: [kuberentes]
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v3
+    scan-config:
+        runs-on: ubuntu-latest
+        steps:
+            - name: Checkout source code
+              uses: actions/checkout@v3
 
-      - name: Validate if commit follows the pattern in description "#<number> - description"
-        run: |
-          if ! git log -1 --pretty=%B | grep -qE '.+'; then
-            echo "Error: Commit description does not follow the pattern 'description'"
-            exit 1
-          fi
+            - name: Validate package.json
+              run: |
+                  PACKAGE_NAME=$(cat package.json | jq -r '.name')
+                  PRIVATE=$(cat package.json | jq -r '.private')
+                  PUBLISH_CONFIG=$(cat package.json | jq '.publishConfig')
+                  REPOSITORY=$(cat package.json | jq '.repository')
 
-  scan-config:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout source code
-        uses: actions/checkout@v3
+                  if [[ ! ${PACKAGE_NAME} =~ ^@[a-zA-Z0-9_-]+/[a-zA-Z0-9_-]+$ ]]; then
+                    echo "Error: attribute name is not in the format @<company>/<name>"
+                    exit 1
+                  fi
 
-      - name: Validate package.json
-        run: |
-          PACKAGE_NAME=$(cat package.json | jq -r '.name')
-          PRIVATE=$(cat package.json | jq -r '.private')
-          PUBLISH_CONFIG=$(cat package.json | jq '.publishConfig')
-          REPOSITORY=$(cat package.json | jq '.repository')
+                  if [[ ${PUBLISH_CONFIG} == "null" ]]; then
+                    echo "Error: publishConfig is required"
+                    exit 1
+                  fi
 
-          if [[ ! ${PACKAGE_NAME} =~ ^@[a-zA-Z0-9_-]+/[a-zA-Z0-9_-]+$ ]]; then
-            echo "Error: attribute name is not in the format @<company>/<name>"
-            exit 1
-          fi
+                  if [[ ${REPOSITORY} == "null" ]]; then
+                    echo "Error: repository is required"
+                    exit 1
+                  fi
 
-          if [[ ${PUBLISH_CONFIG} == "null" ]]; then
-            echo "Error: publishConfig is required"
-            exit 1
-          fi
+                  if [[ ${PRIVATE} == "true" ]]; then
+                    echo "Warning: private attribute is set to true, changing to false"
+                    jq '.private = false' package.json > package.json.tmp && mv package.json.tmp package.json
+                  fi
 
-          if [[ ${REPOSITORY} == "null" ]]; then
-            echo "Error: repository is required"
-            exit 1
-          fi
+    scan-packages:
+        timeout-minutes: 5
+        runs-on: ubuntu-latest
+        continue-on-error: true
 
-          if [[ ${PRIVATE} == "true" ]]; then
-            echo "Warning: private attribute is set to true, changing to false"
-            jq '.private = false' package.json > package.json.tmp && mv package.json.tmp package.json
-          fi
+        steps:
+            - name: Checkout Code
+              uses: actions/checkout@v3
 
-  scan-packages:
-    timeout-minutes: 5
-    runs-on: ubuntu-latest
-    continue-on-error: true
+            - name: Scan Packages
+              run: npm audit
+              env:
+                  CI: true
 
-    steps:
-      - name: Checkout Code
-        uses: actions/checkout@v3
+    change-version:
+        needs: [ scan-git, scan-config, scan-packages ]
+        timeout-minutes: 1
+        runs-on: ubuntu-latest
 
-      - name: Scan Packages
-        run: npm audit
-        env:
-          CI: true
+        permissions:
+            contents: write
 
-  change-version:
-    needs: [ scan-git, scan-config, scan-packages ]
-    timeout-minutes: 1
-    runs-on: ubuntu-latest
+        steps:
+            - name: Checkout Code
+              uses: actions/checkout@v3
 
-    permissions:
-      contents: write
+            - name: Set up Node.js
+              uses: actions/setup-node@v3
+              with:
+                  node-version: ${{ env.ENV_NODE_VERSION }}
 
-    steps:
-      - name: Checkout Code
-        uses: actions/checkout@v3
+            - name: Configure git
+              run: |
+                  git config --global user.name ${{ env.ENV_GIT_USERNAME }}
+                  git config --global user.email ${{ env.ENV_GIT_EMAIL }}
 
-      - name: Set up Node.js
-        uses: actions/setup-node@v3
-        with:
-          node-version: ${{ env.ENV_NODE_VERSION }}
+            - name: Change version package.json for bugfix-prerelease
+              run: npm version prerelease
 
-      - name: Configure git
-        run: |
-          git config --global user.name ${{ env.ENV_GIT_USERNAME }}
-          git config --global user.email ${{ env.ENV_GIT_EMAIL }}
+            - name: Push changes
+              run: git push
 
-      - name: Change version package.json for bugfix-prerelease
-        run: npm version prerelease
+    packages:
+        needs: [ change-version ]
+        timeout-minutes: 1
+        runs-on: ubuntu-latest
 
-      - name: Push changes
-        run: git push
+        steps:
+            - name: Checkout Code
+              uses: actions/checkout@v3
 
-  packages:
-    needs: [ change-version ]
-    timeout-minutes: 1
-    runs-on: ubuntu-latest
+            - name: Set up Node.js
+              uses: actions/setup-node@v3
+              with:
+                  node-version: ${{ env.ENV_NODE_VERSION }}
 
-    steps:
-      - name: Checkout Code
-        uses: actions/checkout@v3
+            - name: Install dependencies
+              run: npm ci --force
 
-      - name: Set up Node.js
-        uses: actions/setup-node@v3
-        with:
-          node-version: ${{ env.ENV_NODE_VERSION }}
+            - name: Cache node modules
+              id: cache-npm
+              uses: actions/cache@v3
+              env:
+                  cache-name: cache-node-modules
+              with:
+                  path: ~/.npm
+                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
+                  restore-keys: |
+                      ${{ runner.os }}-build-${{ env.cache-name }}-
 
-      - name: Install dependencies
-        run: npm ci --force
+    quality-eslint:
+        timeout-minutes: 1
+        runs-on: ubuntu-latest
+        needs: [ packages ]
 
-      - name: Cache node modules
-        id: cache-npm
-        uses: actions/cache@v3
-        env:
-          cache-name: cache-node-modules
-        with:
-          path: ~/.npm
-          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
-          restore-keys: |
-            ${{ runner.os }}-build-${{ env.cache-name }}-
+        steps:
+            - name: Checkout Code
+              uses: actions/checkout@v3
 
-  quality-eslint:
-    timeout-minutes: 1
-    runs-on: ubuntu-latest
-    needs: [ packages ]
+            - name: Set up Node.js
+              uses: actions/setup-node@v3
+              with:
+                  node-version: ${{ env.ENV_NODE_VERSION }}
 
-    steps:
-      - name: Checkout Code
-        uses: actions/checkout@v3
+            - name: Restore Cached Dependencies
+              uses: actions/cache@v3
+              id: npm-cache
+              env:
+                  cache-name: cache-node-modules
+              with:
+                  path: ~/.npm
+                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
+                  restore-keys: |
+                      ${{ runner.os }}-build-${{ env.cache-name }}-
 
-      - name: Set up Node.js
-        uses: actions/setup-node@v3
-        with:
-          node-version: ${{ env.ENV_NODE_VERSION }}
+            - name: Install Dependencies
+              run: npm ci --force
 
-      - name: Restore Cached Dependencies
-        uses: actions/cache@v3
-        id: npm-cache
-        env:
-          cache-name: cache-node-modules
-        with:
-          path: ~/.npm
-          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
-          restore-keys: |
-            ${{ runner.os }}-build-${{ env.cache-name }}-
+            - name: Lint
+              run: npm run lint
 
-      - name: Install Dependencies
-        run: npm ci --force
+    quality-test-unit:
+        timeout-minutes: 1
+        runs-on: ubuntu-latest
+        needs: [ packages ]
 
-      - name: Lint
-        run: npm run lint
+        steps:
+            - name: Checkout Code
+              uses: actions/checkout@v3
 
-  quality-test-unit:
-    timeout-minutes: 1
-    runs-on: ubuntu-latest
-    needs: [ packages ]
+            - name: Set up Node.js
+              uses: actions/setup-node@v3
+              with:
+                  node-version: ${{ env.ENV_NODE_VERSION }}
 
-    steps:
-      - name: Checkout Code
-        uses: actions/checkout@v3
+            - name: Restore Cached Dependencies
+              uses: actions/cache@v3
+              id: npm-cache
+              env:
+                  cache-name: cache-node-modules
+              with:
+                  path: ~/.npm
+                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
+                  restore-keys: |
+                      ${{ runner.os }}-build-${{ env.cache-name }}-
 
-      - name: Set up Node.js
-        uses: actions/setup-node@v3
-        with:
-          node-version: ${{ env.ENV_NODE_VERSION }}
+            - name: Install Dependencies
+              run: npm ci --force
 
-      - name: Restore Cached Dependencies
-        uses: actions/cache@v3
-        id: npm-cache
-        env:
-          cache-name: cache-node-modules
-        with:
-          path: ~/.npm
-          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
-          restore-keys: |
-            ${{ runner.os }}-build-${{ env.cache-name }}-
+            - name: Lint
+              run: npm run test
 
-      - name: Install Dependencies
-        run: npm ci --force
+    quality-test-integration:
+        timeout-minutes: 1
+        runs-on: ubuntu-latest
+        needs: [ packages ]
 
-      - name: Lint
-        run: npm run test
+        steps:
+            - name: Checkout Code
+              uses: actions/checkout@v3
 
-  quality-test-integration:
-    timeout-minutes: 1
-    runs-on: ubuntu-latest
-    needs: [ packages ]
+            - name: Set up Node.js
+              uses: actions/setup-node@v3
+              with:
+                  node-version: ${{ env.ENV_NODE_VERSION }}
 
-    steps:
-      - name: Checkout Code
-        uses: actions/checkout@v3
+            - name: Restore Cached Dependencies
+              uses: actions/cache@v3
+              id: npm-cache
+              env:
+                  cache-name: cache-node-modules
+              with:
+                  path: ~/.npm
+                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
+                  restore-keys: |
+                      ${{ runner.os }}-build-${{ env.cache-name }}-
 
-      - name: Set up Node.js
-        uses: actions/setup-node@v3
-        with:
-          node-version: ${{ env.ENV_NODE_VERSION }}
+            - name: Install Dependencies
+              run: npm ci --force
 
-      - name: Restore Cached Dependencies
-        uses: actions/cache@v3
-        id: npm-cache
-        env:
-          cache-name: cache-node-modules
-        with:
-          path: ~/.npm
-          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
-          restore-keys: |
-            ${{ runner.os }}-build-${{ env.cache-name }}-
+            - name: Lint
+              run: npm run test:e2e
 
-      - name: Install Dependencies
-        run: npm ci --force
+    quality-test-coverage:
+        timeout-minutes: 1
+        runs-on: ubuntu-latest
+        needs: [ packages ]
 
-      - name: Lint
-        run: npm run test:e2e
+        steps:
+            - name: Checkout Code
+              uses: actions/checkout@v3
 
-  quality-test-coverage:
-    timeout-minutes: 1
-    runs-on: ubuntu-latest
-    needs: [ packages ]
+            - name: Set up Node.js
+              uses: actions/setup-node@v3
+              with:
+                  node-version: ${{ env.ENV_NODE_VERSION }}
 
-    steps:
-      - name: Checkout Code
-        uses: actions/checkout@v3
+            - name: Restore Cached Dependencies
+              uses: actions/cache@v3
+              id: npm-cache
+              env:
+                  cache-name: cache-node-modules
+              with:
+                  path: ~/.npm
+                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
+                  restore-keys: |
+                      ${{ runner.os }}-build-${{ env.cache-name }}-
 
-      - name: Set up Node.js
-        uses: actions/setup-node@v3
-        with:
-          node-version: ${{ env.ENV_NODE_VERSION }}
+            - name: Install Dependencies
+              run: npm ci --force
 
-      - name: Restore Cached Dependencies
-        uses: actions/cache@v3
-        id: npm-cache
-        env:
-          cache-name: cache-node-modules
-        with:
-          path: ~/.npm
-          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
-          restore-keys: |
-            ${{ runner.os }}-build-${{ env.cache-name }}-
-
-      - name: Install Dependencies
-        run: npm ci --force
-
-      - name: Coverage
-        run: npm run test:cov
+            - name: Coverage
+              run: npm run test:cov
